server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.191.211:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&useSSL=false&allowMultiQueries=true
    username: root
    password: Whp/0620
  redis:
    host: 39.106.191.211
    port: 6379
    database: 8
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath*:**.*/*.xml

logging:
  level:
    com.sinosoft.mybatis.mapper: debug

ftp:
  host: 39.106.191.211
  port: 22
  username: sftpuser
  password: Whp/0610
  remoteFilePath: /upload
  localFilePath: /home/appian/Downloads/
